### ISSUE TITLE
Some Bugs and Errors

### ISSUE THREAD

**Issue by TT32-C** [radimitrov/CSharpShellApp#133]
Some of errors and bug I have incounter:

1.Adding Reference
 •adding internal and xternal reference show an error 

Java.Lang.NoSuchMethodError: no non-static method "Landroid/view/View;.setFocusedByDefault(Z)V"
  at Java.Interop.JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <1921523bc22e407fa9a0855bdae29335>:0 
  at Java.Interop.JniType.GetInstanceMethod (System.String name, System.String signature) [0x0000c] in <1921523bc22e407fa9a0855bdae29335>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.GetMethodInfo (System.String encodedMember) [0x00031] in <1921523bc22e407fa9a0855bdae29335>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001c] in <1921523bc22e407fa9a0855bdae29335>:0 
  at Android.Views.View.set_FocusedByDefault (System.Boolean value) [0x00022] in <d6d61ecb611a47bdb0740fd298231936>:0 
  at CSharp_Shell.Activities.MainActivity+<>c__DisplayClass134_0.<AssembliesButton_Click>b__0 (System.Object s, AndroidX.AppCompat.Widget.Toolbar+MenuItemClickEventArgs e) [0x00164] in <f9520a05709348ddb8f1c11856d4d3e9>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <ac5dda0190f24d829c27844a2bccc1dd>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <d6d61ecb611a47bdb0740fd298231936>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d6d61ecb611a47bdb0740fd298231936>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <d6d61ecb611a47bdb0740fd298231936>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.75(intptr,intptr)
  --- End of managed Java.Lang.NoSuchMethodError stack trace ---
java.lang.NoSuchMethodError: no non-static method "Landroid/view/View;.setFocusedByDefault(Z)V"
	at mono.androidx.appcompat.widget.Toolbar_OnMenuItemClickListenerImplementor.n_onMenuItemClick(Native Method)
	at mono.androidx.appcompat.widget.Toolbar_OnMenuItemClickListenerImplementor.onMenuItemClick(Toolbar_OnMenuItemClickListenerImplementor.java:30)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:346)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1577)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3970)
	at android.widget.AbsListView$7.run(AbsListView.java:6065)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7406)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by TT32-C** [comment]
2.Adding Packages
•when installing nuget packages in the nuget browser throws an exception

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <ac5dda0190f24d829c27844a2bccc1dd>:0 
  at System.Linq.Enumerable.ElementAt[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Int32 index) [0x00031] in <0276d471a52f46a2bbf33af5074c0b7a>:0 
  at CSharp_Shell.Adapters.PackagesAdapter.BtnInstall_Click (System.Object sender, System.EventArgs e) [0x00057] in <f9520a05709348ddb8f1c11856d4d3e9>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <ac5dda0190f24d829c27844a2bccc1dd>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <d6d61ecb611a47bdb0740fd298231936>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d6d61ecb611a47bdb0740fd298231936>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <d6d61ecb611a47bdb0740fd298231936>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.75(intptr,intptr)

**Comment by radimitrov** [comment]
I think I just fixed all of these for the next update in about a day. 
However I'm not sure about the packages install error. 
It has to be an empty versions request response. Is the versions box empty when it happens?
Hopefully that is now also fixed or at least less frequent.

**Comment by TT32-C** [comment]
Ahhh that's great to hear, Yeah about the nuget package when I browse nuget and press the intall button , it throws that exception but the version box is not empty.

**Comment by radimitrov** [comment]
Hmm, I'm not sure then. I couldn't replicate the issue. If it goes away after the next update, then it was probably the package versions. If not drop me your Android version here and I will see if it a platform issue somehow.

**Comment by TT32-C** [comment]
Ahh I see , I've just updated the app now to v2.5.65 and the problem goes away
