### ISSUE TITLE
 I can't create projects.

### ISSUE THREAD

**Issue by WithoutCoffeeBr** [radimitrov/CSharpShellApp#237]
Could you create a custom one for Android12? I would really like to use the new version of the app, but I'm facing difficulties

**Comment by WithoutCoffeeBr** [comment]
I wanted to take advantage and leaves this error that happens to exports the apk

System.ArgumentNullException: Value cannot be null. (Parameter 'trees[3]')
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.AddSyntaxTrees(IEnumerable`1 trees)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(String assemblyName, CSharpCompilationOptions options, IEnumerable`1 syntaxTrees, IEnumerable`1 references, CSharpCompilation previousSubmission, Type returnType, Type hostObjectType, Boolean isSubmission)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(String assemblyName, IEnumerable`1 syntaxTrees, IEnumerable`1 references, CSharpCompilationOptions options)
   at CSharpShellCore.IDE.Workspace.GetCompilation(OutputKind outKind, Boolean debugMode, Boolean exportApk, Boolean exportAssembly)
   at CSharpShellCore.IDE.Workspace.Compile(Stream peStream, Stream pdbStream, IEnumerable`1 resources, OutputKind outKind, Boolean debugMode, Boolean exportApk, Boolean exportAssembly)
   at CSharpShellCore.IDE.Workspace.Compile(Stream peStream, Stream pdbStream, OutputKind outKind, Boolean debugMode, Boolean exportApk, Boolean exportAssembly)
   at CSharpShellCore.Activities.MainActivity.<>c__DisplayClass223_0.<Run>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at CSharpShellCore.Activities.MainActivity.Run(Boolean debugMode, Boolean exportApk, String args)

**Comment by radimitrov** [comment]
Not an Android 12 issue. I've fixed it for next release

**Comment by WithoutCoffeeBr** [comment]
I saw that the problems were fixed, but I ended up running into another one. I am exporting a console project to apk, but the content is not displayed.

**Comment by radimitrov** [comment]
Are you using System.Console? I think I haven't hooked it up to CSharpShell.Console in the apk plugin (did it just now).
Recommend using the latter anyway since WriteLine is practically the only method that won't throw a PlatformNotImplementedException with System.Console.

**Comment by WithoutCoffeeBr** [comment]
I did the test with readline, it seems to be working. I believe there may be a color problem because I can write in the console.

**Comment by WithoutCoffeeBr** [comment]
I tried to change the color but it didn't work.

**Comment by WithoutCoffeeBr** [comment]
There are no errors in the exported apk, only the display of what does not occur.

I this System.Console error only occurs in the IDE

**Comment by WithoutCoffeeBr** [comment]
I used readline to test and I can even type, but the text is not displayed. I tried changing the font color and it didn't work.
