### ISSUE TITLE
WifiManager.DhcpInfo exception

### ISSUE THREAD

**Issue by Crazyx001** [radimitrov/CSharpShellApp#25]
I get an runtime exception when getting WifiManager.DhcpInfo

Java.Lang.SecurityException: WifiService: Neither user 10155 nor current process has android.permission.ACCESS_WIFI_STATE. ---> Android.OS.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:1822)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1850)
	at com.android.server.wifi.WifiServiceImpl.enforceAccessPermission(WifiServiceImpl.java:805)
	at com.android.server.wifi.WifiServiceImpl.getDhcpInfo(WifiServiceImpl.java:2383)
	at android.net.wifi.IWifiManager$Stub.onTransact(IWifiManager.java:408)

   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <af1c6fdcff1a4da4a0e44a8cdef352da>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <af1c6fdcff1a4da4a0e44a8cdef352da>:0 
  at Android.Net.Wifi.WifiManager.get_DhcpInfo () [0x0000a] in <d706cf8faf5542949900cf6d57864528>:0 
  at CSharp_Shell.Program.Main () [0x000e9] in <d67d474955b54b7f8f7e72cf5b0151ee>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <9a7f37f8b53d493eb264b2e0d3b2956a>:0 
  --- End of managed Java.Lang.SecurityException stack trace ---
java.lang.SecurityException: WifiService: Neither user 10155 nor current process has android.permission.ACCESS_WIFI_STATE.
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.net.wifi.IWifiManager$Stub$Proxy.getDhcpInfo(IWifiManager.java:1566)
	at android.net.wifi.WifiManager.getDhcpInfo(WifiManager.java:1897)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:1822)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1850)
	at com.android.server.wifi.WifiServiceImpl.enforceAccessPermission(WifiServiceImpl.java:805)
	at com.android.server.wifi.WifiServiceImpl.getDhcpInfo(WifiServiceImpl.java:2383)
	at android.net.wifi.IWifiManager$Stub.onTransact(IWifiManager.java:408)

**Comment by radimitrov** [comment]
I can't add duzens of permissions that aren't actually used in the C# Shell application itself.
Export your project as an apk. You can add permissions there.

**Comment by Crazyx001** [comment]
OK, thanks
