### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hirman21** [radimitrov/CSharpShellApp#253]
System.NullReferenceException: Object reference not set to an instance of an object
   at RoslynSoftDebugger.CSharpDebugCreator.DetectStatements(SyntaxNode node, List`1 statements, List`1 variables)
   at RoslynSoftDebugger.CSharpDebugCreator.DetectStatements(BaseMethodDeclarationSyntax method)
   at RoslynSoftDebugger.CSharpDebugCreator.InsertBreakpoints(SyntaxTree tree, Boolean makeOnlyAsyncMethodsDebuggable)
   at RoslynSoftDebugger.CSharpDebugCreator.MakeDebuggable(SyntaxTree tree, Boolean makeOnlyAsyncMethodsDebuggable)
   at CSharpShellCore.IDE.Workspace.MakeDebuggable(SyntaxTree tree)
   at CSharpShellCore.IDE.Workspace.<>c.<GetCompilation>b__152_0(SyntaxTree x)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3[[Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].<CombineSelectors>b__0(SyntaxTree x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2[[Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Linq.Enumerable.AppendPrependIterator`1[[Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].LoadFromEnumerator()
   at System.Linq.Enumerable.AppendPrepend1Iterator`1[[Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__42`1[[Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree, Microsoft.CodeAnalysis.CSharp, Version=4.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.AddSyntaxTrees(IEnumerable`1 trees)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(String assemblyName, CSharpCompilationOptions options, IEnumerable`1 syntaxTrees, IEnumerable`1 references, CSharpCompilation previousSubmission, Type returnType, Type hostObjectType, Boolean isSubmission)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(String assemblyName, IEnumerable`1 syntaxTrees, IEnumerable`1 references, CSharpCompilationOptions options)
   at CSharpShellCore.IDE.Workspace.GetCompilation(OutputKind outKind, Boolean debugMode, Boolean exportApk, Boolean exportAssembly)
   at CSharpShellCore.IDE.Workspace.Compile(Stream peStream, Stream pdbStream, IEnumerable`1 resources, OutputKind outKind, Boolean debugMode, Boolean exportApk, Boolean exportAssembly)
   at CSharpShellCore.IDE.Workspace.Compile(Stream peStream, Stream pdbStream, OutputKind outKind, Boolean debugMode, Boolean exportApk, Boolean exportAssembly)
   at CSharpShellCore.Activities.MainActivity.<>c__DisplayClass228_0.<Run>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at CSharpShellCore.Activities.MainActivity.Run(Boolean debugMode, Boolean exportApk, String args)

**Comment by radimitrov** [comment]
Should be fixed in the next update
