### ISSUE TITLE
After get error / crash

### ISSUE THREAD

**Issue by QPLAYid** [radimitrov/CSharpShellApp#258]
System.Threading.ThreadInterruptedException: Thread was interrupted from a waiting state.
   at System.Threading.WaitSubsystem.ThreadWaitInfo.Sleep(Int32 timeoutMilliseconds, Boolean interruptible)
   at System.Threading.WaitSubsystem.Sleep(Int32 timeoutMilliseconds, Boolean interruptible)
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at System.Threading.SpinWait.SpinOnceCore(Int32 sleep1Threshold)
   at System.Threading.SpinWait.SpinOnce(Int32 sleep1Threshold)
   at System.Threading.Tasks.Task.SpinWait(Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at CSharpShellCore.IDE.Views.ConsoleView.SetSelection(Int32 index)
   at CSharpShellCore.Activities.MainActivity.ShowRuntimeError(String v)
   at CSharpShellCore.Activities.MainActivity.ShowRuntimeError(Exception ex)
   at CSharpShellCore.Activities.MainActivity.<>c__DisplayClass228_0.<Run>g__ShowErrorAndReset|6(Exception ex)
   at CSharpShellCore.Activities.MainActivity.<>c__DisplayClass228_0.<Run>b__8()
   at System.Threading.Thread.StartCallback()

Verison app: lates version
Os android 12
Rom miui 13
Decive redmi note 10 pro

**Comment by radimitrov** [comment]
Should be fixed now

**Comment by QPLAYid** [comment]
> Should be fixed now

Yes well done
