### ISSUE TITLE
when I open file or project CSharpShell is crash and stop working

### ISSUE THREAD

**Issue by Abdul-Mohiz** [radimitrov/CSharpShellApp#284]
I seved my MAUI project and closed app later I open app and want to open my previous MAUI project when I select folder and click on Open the app is being crashed and after it nothing program can be run or execute when I run some thing I seen this alert msg 👇👇👇
------------------------
System.NullReferenceException: Object reference not set to an instance of an object
   at CSharpShellCore.Activities.MainActivity.OnOptionsItemSelected(IMenuItem item)
   at Android.App.Activity.n_OnOptionsItemSelected_Landroid_view_MenuItem_(IntPtr jnienv, IntPtr native__this, IntPtr native_item)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_Z(_JniMarshal_PPL_Z callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
-------------------
and if I open app I see this👇👇👇
-----------------
System.ApplicationException: Not a project or source file:  /storage/emulated/0/CSharpShell/Projects/Maui/App.xaml.
Text files (txt/xml/json) should be editable from the project view if in project folder. Otherwise the file manager's 'Open...' dropdown option can be used with an external editor.
   at CSharpShellCore.Activities.MainActivity.LoadProject(String filepath)
   at CSharpShellCore.Activities.MainActivity.LoadCurrentProject()
   at CSharpShellCore.Activities.MainActivity.<>c__DisplayClass240_0.<<InitCode>b__2>d.MoveNext()
--------------------
but I have project.

after this I clear all data of app and open its work as a normal. if i create new project then alright but if I open previous project I got error

I hope this feedback improve your app
thanks!
Abdul Mohiz

**Comment by radimitrov** [comment]
@Abdul-Mohiz The NullReferenceException is because the previous project was unloaded but the new one failed to load. I'm going to fix that part. 
The other Exception is actually telling you what is wrong. You are trying to open "App.xaml" as a project file, which it isn't. Open the ".csproj" project file instead.

**Comment by Abdul-Mohiz** [comment]
thanks @radimitrov for solving my problem
