### ISSUE TITLE
automatically capitalized

### ISSUE THREAD

**Issue by Rystars** [radimitrov/CSharpShellApp#294]
https://github.com/radimitrov/CSharpShellApp/assets/96302690/077f90f5-9a62-46d5-b8b7-363845916757

see that when you create a new file on the tab, the first letter in the namespace is lowercase, but when you finish creating the file, the first letter in the namespace becomes uppercase

**Comment by devastaza** [comment]
Yes I agree. Every time I have to manually fix it

**Comment by radimitrov** [comment]
Looks like I implemented it like this intentionally for naming conventions ~2 years ago. Logic seems to be that C# is pascal-case in 99.8% of use-cases so make that a bit easier with Android keyboards. 
However in hindsight that isn't the best idea and it might even mislead beginners to think class names are case insensitive. I'll remove autocapitalization here.

**Comment by Rystars** [comment]
> Looks like I implemented it like this intentionally for naming conventions ~2 years ago. Logic seems to be that C# is pascal-case in 99.8% of use-cases so make that a bit easier with Android keyboards. However in hindsight that isn't the best idea and it might even mislead beginners to think class names are case insensitive. I'll remove autocapitalization here.

one more if you can please add like this in the keyboard

**Comment by radimitrov** [comment]
@Rystars That should show up if you enable text composition in the app's keyboard settings. Should work with GBoard, however if you experience input problems you will need to disable it again.

**Comment by Rystars** [comment]
![Screenshot_2023-06-12-19-08-31-878_com radinc csharpshell](https://github.com/radimitrov/CSharpShellApp/assets/96302690/fe5fea5b-988b-459d-9650-10f7c7334db5)

System.NullReferenceException: Object reference not set to an instance of an object
   at CSharpShellCore.Activities.MainActivity.InitProject(String projectFilePath, Boolean calledFromLoadProject)
   at CSharpShellCore.Activities.MainActivity.LoadProject(String filepath)
   at CSharpShellCore.Activities.MainActivity.LoadCurrentProject()
   at CSharpShellCore.Activities.MainActivity.LoadNewProject(String projPath, Boolean showLoadingToast)
   at CSharpShellCore.Activities.MainActivity.OpenFile()

@radimitrov after the update there is no error when opening the project

**Comment by radimitrov** [comment]
@Rystars Can you provide steps to replicate this? Seems to be working. It doesn't seem possible that any recent changes are responsible.

**Comment by Rystars** [comment]
@radimitrov 

https://github.com/radimitrov/CSharpShellApp/assets/96302690/ec4ddf9b-ee3c-4e7a-9620-f873fd6f980c

**Comment by Rystars** [comment]
@radimitrov 

my cellphone is android 10 (Redmi9C)

**Comment by radimitrov** [comment]
@Rystars Then storage access works now? Strange. Some kind of permissions/system glitch, then.

**Comment by Rystars** [comment]
yes now it is working
