### ISSUE TITLE
Can I use ML.NET in MAUI (in your app) even in builded apk? 

### ISSUE THREAD

**Issue by sedoLevi609** [radimitrov/CSharpShellApp#302]
@radimitrov  Because I started  a net maui ML.NET project (and while developing I tested more time), but at a point it throw this exception:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Shuffle input cursor reader failed with an exception
 ---> System.InvalidOperationException: Splitter/consolidator worker encountered exception while consuming source data
 ---> System.DllNotFoundException: CpuMathNative
   at Microsoft.ML.Internal.CpuMath.CpuMathUtils.SumSq(Single mean, ReadOnlySpan`1 src)
   at Microsoft.ML.Transforms.LpNormNormalizingTransformer.Mapper.L2Norm(ReadOnlySpan`1 values, Single mean)
   at Microsoft.ML.Transforms.LpNormNormalizingTransformer.Mapper.<>c__DisplayClass8_0.<MakeGetter>b__5(VBuffer`1& dst)
   at Microsoft.ML.Data.ColumnConcatenatingTransformer.Mapper.BoundColumn.<>c__DisplayClass20_0`1[[System.Single, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<MakeGetter>b__0(VBuffer`1& dst)
   at Microsoft.ML.Data.DataViewUtils.Splitter.InPipe.Impl`1[[Microsoft.ML.Data.VBuffer`1[[System.Single, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.ML.DataView, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].Fill()
   at Microsoft.ML.Data.DataViewUtils.Splitter.<>c__DisplayClass7_1.<ConsolidateCore>b__2()
   --- End of inner exception stack trace ---
   at Microsoft.ML.Data.DataViewUtils.Splitter.Batch.SetAll(OutPipe[] pipes)
   at Microsoft.ML.Data.DataViewUtils.Splitter.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.SynchronizedCursorBase.MoveNext()
   at Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.ProduceAsync()
   --- End of inner exception stack trace ---
   at Microsoft.ML.Transforms.RowShufflingTransformer.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Trainers.TrainingCursorBase.MoveNext()
   at Microsoft.ML.Trainers.SdcaTrainerBase`3[[Microsoft.ML.Trainers.SdcaBinaryTrainerBase`1.BinaryOptionsBase[[Microsoft.ML.Calibrators.CalibratedModelParametersBase`2[[Microsoft.ML.Trainers.LinearBinaryModelParameters, Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.PlattCalibrator, Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Data.BinaryPredictionTransformer`1[[Microsoft.ML.Calibrators.CalibratedModelParametersBase`2[[Microsoft.ML.Trainers.LinearBinaryModelParameters, Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.PlattCalibrator, Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.CalibratedModelParametersBase`2[[Microsoft.ML.Trainers.LinearBinaryModelParameters, Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.PlattCalibrator, Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].TrainCore(IChannel ch, RoleMappedData data, LinearModelParameters predictor, Int32 weightSetCount)
   at Microsoft.ML.Trainers.StochasticTrainerBase`2[[Microsoft.ML.Data.BinaryPredictionTransformer`1[[Microsoft.ML.Calibrators.CalibratedModelParametersBase`2[[Microsoft.ML.Trainers.LinearBinaryModelParameters, Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.PlattCalibrator, Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.CalibratedModelParametersBase`2[[Microsoft.ML.Trainers.LinearBinaryModelParameters, Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.PlattCalibrator, Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2[[Microsoft.ML.Data.BinaryPredictionTransformer`1[[Microsoft.ML.Calibrators.CalibratedModelParametersBase`2[[Microsoft.ML.Trainers.LinearBinaryModelParameters, Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.PlattCalibrator, Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.CalibratedModelParametersBase`2[[Microsoft.ML.Trainers.LinearBinaryModelParameters, Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.PlattCalibrator, Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2[[Microsoft.ML.Data.BinaryPredictionTransformer`1[[Microsoft.ML.Calibrators.CalibratedModelParametersBase`2[[Microsoft.ML.Trainers.LinearBinaryModelParameters, Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.PlattCalibrator, Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.CalibratedModelParametersBase`2[[Microsoft.ML.Trainers.LinearBinaryModelParameters, Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.PlattCalibrator, Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1[[Microsoft.ML.Data.BinaryPredictionTransformer`1[[Microsoft.ML.Calibrators.CalibratedModelParametersBase`2[[Microsoft.ML.Trainers.LinearBinaryModelParameters, Microsoft.ML.StandardTrainers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[Microsoft.ML.Calibrators.PlattCalibrator, Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].Fit(IDataView input)
   at MauiTests.MainPage.BuildTrainModel(MLContext ctx, IDataView set)
   at MauiTests.MainPage..ctor()
   at System.Reflection.ConstructorInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Controls.ShellContent.<>c__DisplayClass19_0.<Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent>b__0()
   at Microsoft.Maui.Controls.ElementTemplate.CreateContent()
   at Microsoft.Maui.Controls.Internals.DataTemplateExtensions.CreateContent(DataTemplate self, Object item, BindableObject container)
   at Microsoft.Maui.Controls.ShellContent.Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2)

And this is the code of the MainPage(didn't change anything else yet):

using System;
using System.IO;
using Microsoft.Maui;
using Microsoft.Maui.Controls;
using Microsoft.ML;
using Microsoft.ML.Data;
using static Microsoft.ML.DataOperationsCatalog;
using MauiTests;
using System.Collections.Generic;

namespace MauiTests
{
	public partial class MainPage : ContentPage
	{
		string path = Path.Combine("/storage/emulated/0/Download", "yelp_labelled.txt");
		
		public MainPage()
		{
			InitializeComponent();
            MLContext ctx = new MLContext();
			TrainTestData dataView = LoadData(ctx);
			ITransformer model = BuildTrainModel(ctx,dataView.TrainSet);
		}
		
		TrainTestData LoadData(MLContext ctx)
		{
			Random r = new Random();
			List<SentimentData> datas = new List<SentimentData>();
			for(int i = 'a'; i <= 'z'; i++)
			{
				datas.Add(new SentimentData{SentimentText = i.ToString(),Sentiment = r.Next(0,2) == 0 ? true : false});
			}
			IDataView dataView = ctx.Data.LoadFromEnumerable<SentimentData>(datas);
			TrainTestData splitted = ctx.Data.TrainTestSplit(dataView,testFraction: 0.2);
			return splitted;
		}
		
    	ITransformer BuildTrainModel(MLContext ctx,IDataView set)
		{
			var estimator = ctx.Transforms.Text.FeaturizeText(outputColumnName: "Features",inputColumnName: nameof(SentimentData.SentimentText)).Append(ctx.BinaryClassification.Trainers.SdcaLogisticRegression(labelColumnName: "Label",featureColumnName: "Features"));
			var model = estimator.Fit(set);
			return model;
		}
	}

	public class SentimentData
	{		
		[LoadColumn(0)]
		public string SentimentText;

		[LoadColumn(1), ColumnName("Label")]
		public bool Sentiment;
	}

	public class SentimentPrediction : SentimentData
	{

		[ColumnName("PredictedLabel")]
		public bool Prediction { get; set; }

		public float Probability { get; set; }

		public float Score { get; set; }
	}
}

Please help me! I hope you can solve it(i somewhere found that ml.net should work in net maui)

**Comment by radimitrov** [comment]
@sedoLevi609  Short answer seems to be no.

CpuMathNative is seems to be referring to a native ".so" dependency (C++ library).
I don't think I've implemented adding them from packages runtime directories? I will check and do so if not.
Packages with native dependencies can only work in a built APK since C++ libraries can't be dynamically loaded in an app.

However I remember something about ML.NET not supporting training of models in Xamarin. This seems to be pretty much unchanged. Take a look at the runtimes directory of the package. No ARM64 library, empty folder. So it won't work on smartphones. I don't know if they are planning to add an ARM64 build.

![screenshot_20230718_132447](https://github.com/radimitrov/CSharpShellApp/assets/56889141/c95f2154-d1a2-44a3-a496-44a6d0531f9e)

**Comment by sedoLevi609** [comment]
Thanks anyway
