### ISSUE TITLE
FileNotFoundException when compiling

### ISSUE THREAD

**Issue by KUNGERMOoN** [radimitrov/CSharpShellApp#319]
Compiling [this](https://e.pcloud.link/publink/show?code=XZ6TBWZomw7YLmzNyYVv4NAbWRnn05rDszV) project throws an error: (Note that the path in the error message contains one backslash instead of slash)
```System.IO.FileNotFoundException: Could not find file '/storage/emulated/0/Android/data/com.radinc.csharpshell/files/ef/Generators\BundleProgramGenerator.cs'.
File name: '/storage/emulated/0/Android/data/com.radinc.csharpshell/files/ef/Generators\BundleProgramGenerator.cs'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Interop.CheckIo(Error error, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.UnixFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at CSharpShellCore.IDE.Workspace.get_SyntaxTrees()
   at CSharpShellCore.IDE.Workspace.GetCompilation(OutputKind outKind, Boolean debugMode, Boolean exportApk, Boolean exportAssembly, String xamlDesignerType)
   at CSharpShellCore.IDE.Workspace.Compile(Stream peStream, Stream pdbStream, IEnumerable`1 resources, OutputKind outKind, Boolean debugMode, Boolean exportApk, Boolean exportAssembly, String xamlDesignerType)
   at CSharpShellCore.IDE.Workspace.Compile(Stream peStream, Stream pdbStream, OutputKind outKind, Boolean debugMode, Boolean exportApk, Boolean exportAssembly, String xamlDesignerType)
   at CSharpShellCore.Activities.MainActivity.<>c__DisplayClass241_0.<Run>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at CSharpShellCore.Activities.MainActivity.Run(Boolean debugMode, Boolean exportApk, String xamlDesignerType, String args, Action customReplacementRunner)```

**Comment by radimitrov** [comment]
I'm almost certain the app compensates for this but open the ".csproj" file and replace all "\" in paths with "/".
