### ISSUE TITLE
Solutions are broken

### ISSUE THREAD

**Issue by sedoLevi609** [radimitrov/CSharpShellApp#374]
@radimitrov 
Solutions worked until the new update. Exception when loading solution: 

System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception.
 ---> System.TypeLoadException: VTable setup of type SQLitePCL.SQLite3Provider_e_sqlite3 failed
   at SQLite.SQLiteConnection..cctor()
   --- End of inner exception stack trace ---
   at CSharpShellCore.IDE.BaseSolution.LoadCurrentProject()
   at CSharpShellCore.IDE.BaseSolution..ctor(String slnPath)
   at CSharpShellCore.Activities.MainActivity.LoadProject(String filepath, Boolean doReset)
   at CSharpShellCore.Activities.MainActivity.LoadCurrentProject(Boolean doReset)
   at CSharpShellCore.IDE.BaseSolution.LoadCurrentProject()
   at CSharpShellCore.IDE.BaseSolution..ctor(String slnPath)
   at CSharpShellCore.Activities.MainActivity.LoadProject(String filepath, Boolean doReset)
   at CSharpShellCore.Activities.MainActivity.LoadCurrentProject(Boolean doReset)
   at CSharpShellCore.Activities.MainActivity.CreateProject(String rootDir, String projName, ProjectType projType, Boolean loadProject, Boolean createLibraryProject, String overrideProjPathLoad)
   at CSharpShellCore.Activities.MainActivity.<>c__DisplayClass417_0.<<CreateProjectDialog>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at CSharpShellCore.IDE.BaseSolution.LoadCurrentProject()
   at CSharpShellCore.IDE.BaseSolution..ctor(String slnPath)
   at CSharpShellCore.Activities.MainActivity.LoadProject(String filepath, Boolean doReset)
   at CSharpShellCore.Activities.MainActivity.LoadCurrentProject(Boolean doReset)
   at CSharpShellCore.Activities.MainActivity.LoadNewProject(String projPath, Boolean showLoadingToast)
   at CSharpShellCore.IDE.BaseSolution.LoadCurrentProject()
   at CSharpShellCore.IDE.BaseSolution..ctor(String slnPath)
   at CSharpShellCore.Activities.MainActivity.LoadProject(String filepath, Boolean doReset)
   at CSharpShellCore.Activities.MainActivity.LoadCurrentProject(Boolean doReset)
   at CSharpShellCore.Activities.MainActivity.LoadNewProject(String projPath, Boolean showLoadingToast)
   at CSharpShellCore.Activities.MainActivity.OpenFile().

Exception when creating solutions:

System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception.
    at CSharpShellCore.IDE.BaseSolution.LoadCurrentProject() in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:74 [74:5-74:40]
    at CSharpShellCore.IDE.BaseSolution..ctor(String slnPath) in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:43 [43:4-43:25]
    at CSharpShellCore.Activities.MainActivity+<LoadProject>d__397.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5674 [5674:5-5674:46]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at System.Runtime.CompilerServices.TaskAwaiter`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult() 
    at CSharpShellCore.Activities.MainActivity+<LoadCurrentProject>d__396.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5598 [5598:4-5598:44]
    at CSharpShellCore.IDE.BaseSolution.LoadCurrentProject() in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:74 [74:5-74:40]
    at CSharpShellCore.IDE.BaseSolution..ctor(String slnPath) in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:43 [43:4-43:25]
    at CSharpShellCore.Activities.MainActivity+<LoadProject>d__397.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5674 [5674:5-5674:46]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at System.Runtime.CompilerServices.TaskAwaiter`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult() 
    at CSharpShellCore.Activities.MainActivity+<LoadCurrentProject>d__396.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5598 [5598:4-5598:44]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at CSharpShellCore.Activities.MainActivity+<CreateProject>d__420.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:7539 [7539:5-7539:32]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at System.Runtime.CompilerServices.TaskAwaiter`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult() 
    at CSharpShellCore.Activities.MainActivity+<>c__DisplayClass417_0+<<CreateProjectDialog>b__3>d.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:7345 [7345:7-7345:203]
    at CSharpShellCore.IDE.BaseSolution.LoadCurrentProject() in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:74 [74:5-74:40]
    at CSharpShellCore.IDE.BaseSolution..ctor(String slnPath) in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:43 [43:4-43:25]
    at CSharpShellCore.Activities.MainActivity+<LoadProject>d__397.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5674 [5674:5-5674:46]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at System.Runtime.CompilerServices.TaskAwaiter`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult() 
    at CSharpShellCore.Activities.MainActivity+<LoadCurrentProject>d__396.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5598 [5598:4-5598:44]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at CSharpShellCore.Activities.MainActivity+<LoadNewProject>d__146.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity.cs:5524 [5524:13-5524:40]
    at CSharpShellCore.IDE.BaseSolution.LoadCurrentProject() in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:74 [74:5-74:40]
    at CSharpShellCore.IDE.BaseSolution..ctor(String slnPath) in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:43 [43:4-43:25]
    at CSharpShellCore.Activities.MainActivity+<LoadProject>d__397.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5674 [5674:5-5674:46]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at System.Runtime.CompilerServices.TaskAwaiter`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult() 
    at CSharpShellCore.Activities.MainActivity+<LoadCurrentProject>d__396.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5598 [5598:4-5598:44]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at CSharpShellCore.Activities.MainActivity+<LoadNewProject>d__146.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity.cs:5524 [5524:13-5524:40]
    at CSharpShellCore.IDE.BaseSolution.LoadCurrentProject() in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:74 [74:5-74:40]
    at CSharpShellCore.IDE.BaseSolution..ctor(String slnPath) in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:43 [43:4-43:25]
    at CSharpShellCore.Activities.MainActivity+<LoadProject>d__397.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5674 [5674:5-5674:46]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at System.Runtime.CompilerServices.TaskAwaiter`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult() 
    at CSharpShellCore.Activities.MainActivity+<LoadCurrentProject>d__396.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5598 [5598:4-5598:44]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at CSharpShellCore.Activities.MainActivity+<CreateProject>d__420.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:7539 [7539:5-7539:32]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at System.Runtime.CompilerServices.TaskAwaiter`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult() 
    at CSharpShellCore.Activities.MainActivity+<>c__DisplayClass417_0+<<CreateProjectDialog>b__3>d.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:7345 [7345:7-7345:203]
    at CSharpShellCore.IDE.BaseSolution.LoadCurrentProject() in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:74 [74:5-74:40]
    at CSharpShellCore.IDE.BaseSolution..ctor(String slnPath) in C:\VS\CSharpShellCore\CSharpShellCore\CSharpShellWorkspace\BaseSolution.cs:43 [43:4-43:25]
    at CSharpShellCore.Activities.MainActivity+<LoadProject>d__397.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5674 [5674:5-5674:46]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at System.Runtime.CompilerServices.TaskAwaiter`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult() 
    at CSharpShellCore.Activities.MainActivity+<LoadCurrentProject>d__396.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:5598 [5598:4-5598:44]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at CSharpShellCore.Activities.MainActivity+<CreateProject>d__420.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:7539 [7539:5-7539:32]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task, ConfigureAwaitOptions options) 
    at System.Runtime.CompilerServices.TaskAwaiter`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult() 
    at CSharpShellCore.Activities.MainActivity+<>c__DisplayClass417_0+<<CreateProjectDialog>b__3>d.MoveNext() in C:\VS\CSharpShellCore\CSharpShellCore\Platforms\Android\Activities\MainActivity_code.cs:7345 [7345:7-7345:203]
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
    at System.Threading.Tasks.Task+<>c.<ThrowAsync>b__128_0(Object state) 
Please fix it.

**Comment by radimitrov** [comment]
Yes, some kind of issue with the latest SQLite packages, it seems... Reverting to the old versions as a hot fix. I'm uploading it now.
